import type { Metadata } from "next";
import { Inter, DM_Sans } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";

const dmSans = DM_Sans({
  subsets:['latin'],
  variable:'--font-sans'}
)

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-map', // Специальный шрифт для карты
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", dmSans.variable, inter.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
